apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-service
  name: config-service
  annotations:
    boot.spring.io/actuator: http://:8080/actuator
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: config-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: kekertop/config-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "config-service"